# Dependabot will run on day 3 of each month at 01:47 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "47 1 3 * *"
    exclude-paths:
      - "doc"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "47 1 3 * *"
    open-pull-requests-limit: 15
